import "dotenv/config";

import { db } from "../lib/db";
import { cars, content, homepageSlides, i18nStrings } from "../lib/db/schema";

const sampleCars = [
  {
    nameGeo: "ასტრა ტერა X",
    nameEn: "Astra Terra X",
    nameRu: "Астра Терра X",
    slug: "astra-terra-x",
    priceFrom: 34900,
    bodyType: "SUV",
    descriptionGeo:
      "თავდაჯერებული საშუალო ზომის SUV ჰიბრიდული პლატფორმით, პანორამული ხედვით და ადაპტური მართვის რეჟიმებით.",
    descriptionEn:
      "A confident midsize SUV with hybrid-ready architecture, panoramic visibility, and adaptive drive modes.",
    descriptionRu:
      "Уверенный среднеразмерный SUV с гибридной платформой, панорамной обзорностью и адаптивными режимами движения.",
    featured: true,
    specs: {
      Power: "245 hp",
      Drivetrain: "AWD",
      Range: "520 km",
      Seats: "5",
    },
    images: [
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1493238792000-8113da705763?auto=format&fit=crop&w=1400&q=80",
    ],
  },
  {
    nameGeo: "ასტრა ურბან E",
    nameEn: "Astra Urban E",
    nameRu: "Астра Урбан E",
    slug: "astra-urban-e",
    priceFrom: 28900,
    bodyType: "Crossover",
    descriptionGeo:
      "ქალაქისთვის შექმნილი კომპაქტური ქროსოვერი სწრაფი დამუხტვითა და მოქნილი მართვით.",
    descriptionEn:
      "Compact crossover engineered for city efficiency with quick charging support and agile handling.",
    descriptionRu:
      "Компактный кроссовер для города с поддержкой быстрой зарядки и маневренной управляемостью.",
    featured: true,
    specs: {
      Power: "190 hp",
      Drivetrain: "FWD",
      Range: "430 km",
      Seats: "5",
    },
    images: [
      "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1400&q=80",
    ],
  },
  {
    nameGeo: "ასტრა ვოიაჯერ 7",
    nameEn: "Astra Voyager 7",
    nameRu: "Астра Вояджер 7",
    slug: "astra-voyager-7",
    priceFrom: 42900,
    bodyType: "SUV",
    descriptionGeo:
      "ოჯახზე ორიენტირებული შვიდადგილიანი მოდელი მოქნილი საბარგულითა და გრძელ დისტანციებზე კომფორტული მგზავრობით.",
    descriptionEn:
      "Family-focused seven-seater with flexible cargo layout, advanced safety suite, and long-range touring comfort.",
    descriptionRu:
      "Семиместная семейная модель с гибкой компоновкой багажника, продвинутой безопасностью и комфортом на дальних поездках.",
    featured: true,
    specs: {
      Power: "260 hp",
      Drivetrain: "AWD",
      Range: "610 km",
      Seats: "7",
    },
    images: [
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1400&q=80",
      "https://images.unsplash.com/photo-1517026575980-3e1e2dedeab4?auto=format&fit=crop&w=1400&q=80",
    ],
  },
];

const homepageContent = {
  hero: {
    eyebrow: "Astra 2026 lineup",
    title: "Contemporary mobility designed around real life.",
    subtitle:
      "Explore connected SUVs and crossovers engineered for efficiency, comfort, and confident everyday driving.",
    primaryCta: { label: "Book a test drive", href: "/book-test-drive" },
    secondaryCta: { label: "Browse models", href: "/models" },
  },
  highlights: [
    {
      title: "Predictive safety systems",
      description: "Lane, distance, and collision assist features standard on core trims.",
    },
    {
      title: "Connected cockpit",
      description: "Large-format displays, voice controls, and OTA software updates.",
    },
    {
      title: "Low-emission performance",
      description: "Hybrid-ready platforms tuned for smooth torque and efficient cruising.",
    },
  ],
};

const sampleSlides = [
  {
    id: "a06260e2-b58a-4ba3-9d7a-8430f6ac2b2f",
    title: "Astra Terra X",
    description: "Confident SUV comfort built for every weekday and every weekend.",
    imageUrl:
      "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1600&q=80",
    ctaLabel: "Explore Terra X",
    ctaHref: "/models/astra-terra-x",
    sortOrder: 0,
    isActive: true,
  },
  {
    id: "2585b170-2ec9-4f65-9b27-4720b4245fd7",
    title: "Astra Urban E",
    description: "Compact electric-ready crossover designed for city agility.",
    imageUrl:
      "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop&w=1600&q=80",
    ctaLabel: "See Urban E",
    ctaHref: "/models/astra-urban-e",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: "b8ac8451-f7dd-42eb-9c9c-04ba3a6a9e2f",
    title: "Astra Voyager 7",
    description: "Seven-seat versatility with road-trip range and premium safety tech.",
    imageUrl:
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=1600&q=80",
    ctaLabel: "View Voyager 7",
    ctaHref: "/models/astra-voyager-7",
    sortOrder: 2,
    isActive: true,
  },
] as const;

const i18nSeedEntries = [
  {
    key: "meta.default.title",
    geo: "ასტრა მოტორსი",
    en: "Astra Motors",
    ru: "Astra Motors",
    description: "Default site title",
  },
  {
    key: "meta.default.description",
    geo: "თანამედროვე SUV-ები და ქროსოვერები კომფორტისთვის, ტექნოლოგიებისთვის და ელექტრო-მობილობისთვის.",
    en: "Modern SUVs and crossovers designed for comfort, technology, and electric-ready mobility.",
    ru: "Современные SUV и кроссоверы для комфорта, технологий и электромобильности.",
    description: "Default site description",
  },
  {
    key: "meta.home.title",
    geo: "მთავარი",
    en: "Home",
    ru: "Главная",
    description: "Home metadata title",
  },
  {
    key: "meta.home.description",
    geo: "აღმოაჩინეთ Astra Motors-ის ახალი ხაზის ავტომობილები.",
    en: "Explore the latest Astra Motors vehicle lineup.",
    ru: "Откройте для себя новую линейку автомобилей Astra Motors.",
    description: "Home metadata description",
  },
  {
    key: "meta.models.title",
    geo: "მოდელები",
    en: "Models",
    ru: "Модели",
    description: "Models metadata title",
  },
  {
    key: "meta.models.description",
    geo: "დაათვალიერეთ Astra Motors-ის SUV-ები და ქროსოვერები.",
    en: "Browse Astra Motors SUVs and crossovers.",
    ru: "Просмотрите SUV и кроссоверы Astra Motors.",
    description: "Models metadata description",
  },
  {
    key: "meta.booking.title",
    geo: "ტესტ დრაივის დაჯავშნა",
    en: "Book Test Drive",
    ru: "Запись на тест-драйв",
    description: "Booking page metadata title",
  },
  {
    key: "meta.booking.description",
    geo: "დაჯავშნეთ ტესტ დრაივი სასურველი მოდელის, ლოკაციისა და დროის მითითებით.",
    en: "Book a test drive with your preferred model, location, and schedule.",
    ru: "Запишитесь на тест-драйв с выбором модели, локации и времени.",
    description: "Booking page metadata description",
  },
  {
    key: "meta.bookingSuccess.title",
    geo: "დაჯავშნა მიღებულია",
    en: "Booking Received",
    ru: "Заявка получена",
    description: "Booking success metadata title",
  },
  {
    key: "meta.bookingSuccess.description",
    geo: "თქვენი ტესტ დრაივის მოთხოვნა მიღებულია.",
    en: "Your test drive request has been received.",
    ru: "Ваша заявка на тест-драйв получена.",
    description: "Booking success metadata description",
  },
  {
    key: "meta.about.title",
    geo: "ჩვენ შესახებ",
    en: "About",
    ru: "О компании",
    description: "About metadata title",
  },
  {
    key: "meta.about.description",
    geo: "გაიგეთ მეტი Astra Motors-ის ხედვისა და მიდგომის შესახებ.",
    en: "Learn more about Astra Motors and our approach to mobility.",
    ru: "Узнайте больше о Astra Motors и нашем подходе к мобильности.",
    description: "About metadata description",
  },
  {
    key: "meta.contact.title",
    geo: "კონტაქტი",
    en: "Contact",
    ru: "Контакты",
    description: "Contact metadata title",
  },
  {
    key: "meta.contact.description",
    geo: "დაგვიკავშირდით გაყიდვების ან სერვისის გუნდთან.",
    en: "Get in touch with our sales and service teams.",
    ru: "Свяжитесь с нашей командой продаж и сервиса.",
    description: "Contact metadata description",
  },

  { key: "brand.name", geo: "Astra Motors", en: "Astra Motors", ru: "Astra Motors", description: "Brand name" },

  { key: "nav.cars", geo: "ავტომობილები", en: "Cars", ru: "Автомобили", description: "Header cars nav" },
  {
    key: "nav.bookTestDrive",
    geo: "ტესტ დრაივი",
    en: "Book Test Drive",
    ru: "Тест-драйв",
    description: "Header book test drive nav",
  },
  { key: "nav.about", geo: "ჩვენ შესახებ", en: "About", ru: "О нас", description: "Header about nav" },
  { key: "nav.contact", geo: "კონტაქტი", en: "Contact", ru: "Контакты", description: "Header contact nav" },

  {
    key: "header.bookTestDrive",
    geo: "დაჯავშნე ტესტ დრაივი",
    en: "Book a test drive",
    ru: "Записаться на тест-драйв",
    description: "Header primary CTA",
  },
  {
    key: "header.openCarsAria",
    geo: "ავტომობილების კატალოგის გახსნა",
    en: "Open cars showcase",
    ru: "Открыть каталог автомобилей",
    description: "Header cars button aria",
  },
  {
    key: "header.openMenuAria",
    geo: "მენიუს გახსნა",
    en: "Open menu",
    ru: "Открыть меню",
    description: "Header open menu aria",
  },
  {
    key: "header.closeMenuAria",
    geo: "მენიუს დახურვა",
    en: "Close menu",
    ru: "Закрыть меню",
    description: "Header close menu aria",
  },
  {
    key: "header.languageSwitcherAria",
    geo: "ენის გადამრთველი",
    en: "Language switcher",
    ru: "Переключатель языка",
    description: "Header language switcher aria",
  },

  {
    key: "admin.shortcut.hotkeyHint",
    geo: "ადმინი: Ctrl/Cmd + Shift + A",
    en: "Admin: Ctrl/Cmd + Shift + A",
    ru: "Админ: Ctrl/Cmd + Shift + A",
    description: "Admin login shortcut hint",
  },
  {
    key: "admin.shortcut.dialogTitle",
    geo: "ადმინის ავტორიზაცია",
    en: "Admin login",
    ru: "Вход администратора",
    description: "Admin shortcut modal title",
  },
  {
    key: "admin.shortcut.dialogDescription",
    geo: "შედით Google ანგარიშით CMS პანელზე გადასასვლელად.",
    en: "Sign in with your allowlisted Google account to open the CMS dashboard.",
    ru: "Войдите через разрешенный Google-аккаунт, чтобы открыть CMS-панель.",
    description: "Admin shortcut modal description",
  },
  {
    key: "admin.cmsShortcut.hotkeyHint",
    geo: "Ctrl/Cmd + Shift + K",
    en: "Ctrl/Cmd + Shift + K",
    ru: "Ctrl/Cmd + Shift + K",
    description: "Admin CMS command palette hotkey hint",
  },
  {
    key: "admin.cmsShortcut.dialogTitle",
    geo: "CMS მალსახმობები",
    en: "CMS shortcut",
    ru: "Быстрые переходы CMS",
    description: "Admin CMS command palette title",
  },
  {
    key: "admin.cmsShortcut.dialogDescription",
    geo: "მოძებნეთ და გახსენით ადმინისტრაციის გვერდი სწრაფად.",
    en: "Search and open any admin destination quickly.",
    ru: "Быстро найдите и откройте нужный раздел админки.",
    description: "Admin CMS command palette description",
  },
  {
    key: "admin.cmsShortcut.searchPlaceholder",
    geo: "CMS გვერდის ძებნა...",
    en: "Search CMS pages...",
    ru: "Поиск по разделам CMS...",
    description: "Admin CMS command palette search placeholder",
  },
  {
    key: "admin.cmsShortcut.emptyState",
    geo: "შესაბამისი შედეგები ვერ მოიძებნა.",
    en: "No matching destinations.",
    ru: "Подходящие разделы не найдены.",
    description: "Admin CMS command palette empty state",
  },
  {
    key: "admin.cmsShortcut.selectHint",
    geo: "ნავიგაცია: ↑ ↓ და Enter",
    en: "Use ↑ ↓ and Enter to navigate",
    ru: "Используйте ↑ ↓ и Enter для выбора",
    description: "Admin CMS command palette keyboard hint",
  },
  {
    key: "admin.cmsShortcut.sections.cms",
    geo: "CMS",
    en: "CMS",
    ru: "CMS",
    description: "Admin CMS command palette section title",
  },
  {
    key: "admin.cmsShortcut.sections.management",
    geo: "მართვა",
    en: "Management",
    ru: "Управление",
    description: "Admin CMS command palette section title",
  },
  {
    key: "admin.cmsShortcut.sections.content",
    geo: "კონტენტი",
    en: "Content",
    ru: "Контент",
    description: "Admin CMS command palette section title",
  },
  {
    key: "admin.cmsShortcut.routes.dashboard.label",
    geo: "დეშბორდი",
    en: "Dashboard",
    ru: "Дашборд",
    description: "Admin CMS command palette route label",
  },
  {
    key: "admin.cmsShortcut.routes.dashboard.description",
    geo: "მთავარი მიმოხილვა და სტატისტიკა.",
    en: "Overview and stats",
    ru: "Общий обзор и статистика",
    description: "Admin CMS command palette route description",
  },
  {
    key: "admin.cmsShortcut.routes.dashboard.keywords",
    geo: "overview,stats,home,მთავარი,სტატისტიკა",
    en: "overview,stats,home",
    ru: "overview,stats,home,обзор,статистика",
    description: "Admin CMS command palette route keywords",
  },
  {
    key: "admin.cmsShortcut.routes.bookings.label",
    geo: "დაჯავშნები",
    en: "Bookings",
    ru: "Заявки",
    description: "Admin CMS command palette route label",
  },
  {
    key: "admin.cmsShortcut.routes.bookings.description",
    geo: "ტესტ დრაივის მოთხოვნები, ლიდები და სტატუსები.",
    en: "Test drive requests, orders, and leads",
    ru: "Заявки на тест-драйв, лиды и статусы",
    description: "Admin CMS command palette route description",
  },
  {
    key: "admin.cmsShortcut.routes.bookings.keywords",
    geo: "bookings,test drive,orders,leads,requests,status,დაჯავშნა,ლიდები",
    en: "bookings,test drive,orders,leads,requests,status",
    ru: "bookings,test drive,orders,leads,requests,status,заявки,лиды",
    description: "Admin CMS command palette route keywords",
  },
  {
    key: "admin.cmsShortcut.routes.cars.label",
    geo: "მანქანები",
    en: "Cars",
    ru: "Автомобили",
    description: "Admin CMS command palette route label",
  },
  {
    key: "admin.cmsShortcut.routes.cars.description",
    geo: "მოდელების კატალოგი და მარაგი.",
    en: "Inventory and model catalog",
    ru: "Склад и каталог моделей",
    description: "Admin CMS command palette route description",
  },
  {
    key: "admin.cmsShortcut.routes.cars.keywords",
    geo: "cars,inventory,models,catalog,მანქანები,მოდელები",
    en: "cars,inventory,models,catalog",
    ru: "cars,inventory,models,catalog,авто,модели",
    description: "Admin CMS command palette route keywords",
  },
  {
    key: "admin.cmsShortcut.routes.homepageSlider.label",
    geo: "მთავარი სლაიდერი",
    en: "Homepage Slider",
    ru: "Слайдер главной",
    description: "Admin CMS command palette route label",
  },
  {
    key: "admin.cmsShortcut.routes.homepageSlider.description",
    geo: "ჰირო კარუსელი და სლაიდების თანმიმდევრობა.",
    en: "Hero carousel slides and ordering",
    ru: "Слайды hero-карусели и их порядок",
    description: "Admin CMS command palette route description",
  },
  {
    key: "admin.cmsShortcut.routes.homepageSlider.keywords",
    geo: "slider,carousel,hero,banner,homepage,სლაიდერი,კარუსელი",
    en: "slider,carousel,hero,banner,homepage",
    ru: "slider,carousel,hero,banner,homepage,слайдер,карусель",
    description: "Admin CMS command palette route keywords",
  },
  {
    key: "admin.cmsShortcut.routes.content.label",
    geo: "საიტის კონტენტი",
    en: "Site Content",
    ru: "Контент сайта",
    description: "Admin CMS command palette route label",
  },
  {
    key: "admin.cmsShortcut.routes.content.description",
    geo: "მთავარი გვერდის ტექსტები და ჰაილაითები.",
    en: "Homepage copy and highlights",
    ru: "Тексты и блоки главной страницы",
    description: "Admin CMS command palette route description",
  },
  {
    key: "admin.cmsShortcut.routes.content.keywords",
    geo: "content,copy,homepage,highlights,text,კონტენტი,ტექსტი",
    en: "content,copy,homepage,highlights,text",
    ru: "content,copy,homepage,highlights,text,контент,текст",
    description: "Admin CMS command palette route keywords",
  },
  {
    key: "admin.cmsShortcut.routes.i18n.label",
    geo: "თარგმანები (i18n)",
    en: "I18n",
    ru: "Переводы (i18n)",
    description: "Admin CMS command palette route label",
  },
  {
    key: "admin.cmsShortcut.routes.i18n.description",
    geo: "GEO / ENG / RUS თარგმანის სტრიქონები.",
    en: "GEO / ENG / RUS strings",
    ru: "Строки переводов GEO / ENG / RUS",
    description: "Admin CMS command palette route description",
  },
  {
    key: "admin.cmsShortcut.routes.i18n.keywords",
    geo: "i18n,translations,localization,geo,en,ru,თარგმანი,ენა",
    en: "i18n,translations,localization,geo,en,ru",
    ru: "i18n,translations,localization,geo,en,ru,переводы,локализация",
    description: "Admin CMS command palette route keywords",
  },
  {
    key: "auth.continueWithGoogle",
    geo: "გაგრძელება Google-ით",
    en: "Continue with Google",
    ru: "Продолжить с Google",
    description: "Continue with Google action",
  },
  { key: "common.cancel", geo: "გაუქმება", en: "Cancel", ru: "Отмена", description: "Common cancel" },
  { key: "common.submit", geo: "გაგზავნა", en: "Submit", ru: "Отправить", description: "Common submit" },
  { key: "common.save", geo: "შენახვა", en: "Save", ru: "Сохранить", description: "Common save" },
  { key: "common.from", geo: "დან", en: "From", ru: "От", description: "Price from prefix" },

  {
    key: "overlay.dialogTitle",
    geo: "Astra-ის ავტომობილების დათვალიერება",
    en: "Browse Astra Cars",
    ru: "Каталог Astra",
    description: "Cars overlay dialog title",
  },
  {
    key: "overlay.dialogDescription",
    geo: "დაათვალიერეთ მოდელები და გახსენით დეტალები.",
    en: "Browse every available model, filter by body type, then open model details.",
    ru: "Просматривайте модели, фильтруйте по типу кузова и открывайте детали.",
    description: "Cars overlay dialog description",
  },
  {
    key: "overlay.closeAria",
    geo: "ავტომობილების ნავიგაციის დახურვა",
    en: "Close cars navigation",
    ru: "Закрыть навигацию по авто",
    description: "Cars overlay close button aria",
  },
  {
    key: "overlay.eyebrow",
    geo: "მოდელების ვიტრინა",
    en: "Model showcase",
    ru: "Витрина моделей",
    description: "Cars overlay eyebrow",
  },
  { key: "overlay.title", geo: "ყველა ავტომობილი", en: "All vehicles", ru: "Все автомобили", description: "Cars overlay title" },
  {
    key: "overlay.searchPlaceholder",
    geo: "მოდელის ძებნა",
    en: "Search model",
    ru: "Поиск модели",
    description: "Cars overlay search placeholder",
  },
  {
    key: "overlay.viewAllModels",
    geo: "ყველა მოდელის ნახვა",
    en: "View all models",
    ru: "Смотреть все модели",
    description: "Cars overlay view all models CTA",
  },
  {
    key: "overlay.vehicleTypes",
    geo: "ავტომობილის ტიპები",
    en: "Vehicle types",
    ru: "Типы кузова",
    description: "Cars overlay vehicle types section",
  },
  {
    key: "overlay.bookTestDrive",
    geo: "ტესტ დრაივის დაჯავშნა",
    en: "Book a test drive",
    ru: "Записаться на тест-драйв",
    description: "Cars overlay book test drive link",
  },
  {
    key: "overlay.discoverModels",
    geo: "ყველა მოდელის აღმოჩენა",
    en: "Discover all models",
    ru: "Открыть все модели",
    description: "Cars overlay discover models link",
  },
  {
    key: "overlay.emptyState",
    geo: "ფილტრს არცერთი მოდელი არ შეესაბამება.",
    en: "No models match this filter.",
    ru: "Нет моделей по выбранному фильтру.",
    description: "Cars overlay empty state",
  },
  { key: "overlay.allTypes", geo: "ყველა", en: "All", ru: "Все", description: "Cars overlay all type option" },

  {
    key: "home.hero.title",
    geo: "თანამედროვე გადაადგილება ყოველდღიური ცხოვრების რიტმში.",
    en: "Contemporary mobility designed around real life.",
    ru: "Современная мобильность, созданная для реальной жизни.",
    description: "Home hero title",
  },
  {
    key: "home.hero.subtitle",
    geo: "აღმოაჩინეთ დაკავშირებული SUV-ები და ქროსოვერები, შექმნილი ეფექტურობისა და კომფორტისთვის.",
    en: "Explore connected SUVs and crossovers engineered for efficiency, comfort, and confident everyday driving.",
    ru: "Откройте для себя SUV и кроссоверы с цифровыми технологиями, созданные для эффективности и комфорта.",
    description: "Home hero subtitle",
  },
  {
    key: "home.hero.primaryCta",
    geo: "ტესტ დრაივის დაჯავშნა",
    en: "Book a test drive",
    ru: "Записаться на тест-драйв",
    description: "Home hero primary CTA",
  },
  {
    key: "home.featured.eyebrow",
    geo: "რჩეული ხაზები",
    en: "Featured range",
    ru: "Рекомендуемая линейка",
    description: "Home featured eyebrow",
  },
  {
    key: "home.featured.title",
    geo: "აირჩიე შენი შემდეგი გზისთვის შესაფერისი მოდელი",
    en: "Drive what fits your next chapter",
    ru: "Выберите модель для вашего следующего этапа",
    description: "Home featured title",
  },
  {
    key: "home.featured.viewAll",
    geo: "ყველა მოდელის ნახვა",
    en: "View all models",
    ru: "Смотреть все модели",
    description: "Home featured view all link",
  },
  {
    key: "home.featured.empty",
    geo: "რჩეული მოდელები ჯერ არ არის დამატებული.",
    en: "No featured models yet. Add them from the admin CMS.",
    ru: "Пока нет рекомендуемых моделей. Добавьте их в CMS.",
    description: "Home featured empty state",
  },
  {
    key: "home.featured.details",
    geo: "დეტალების ნახვა",
    en: "See details",
    ru: "Подробнее",
    description: "Home featured card details button",
  },
  {
    key: "home.highlights.title",
    geo: "რატომ ირჩევენ Astra-ს",
    en: "Why drivers choose Astra",
    ru: "Почему водители выбирают Astra",
    description: "Home highlights section title",
  },
  {
    key: "home.highlights.1.title",
    geo: "უსაფრთხოებაზე ორიენტირებული არქიტექტურა",
    en: "Safety first architecture",
    ru: "Архитектура с приоритетом безопасности",
    description: "Home highlight 1 title",
  },
  {
    key: "home.highlights.1.description",
    geo: "მძღოლის დამხმარე სისტემები სტანდარტულად ყველა ძირითად ვერსიაში.",
    en: "Standard driver-assist systems across the range.",
    ru: "Системы помощи водителю в стандартной комплектации по всей линейке.",
    description: "Home highlight 1 description",
  },
  {
    key: "home.highlights.2.title",
    geo: "ჭკვიანი სალონი",
    en: "Smart cabin systems",
    ru: "Интеллектуальные системы салона",
    description: "Home highlight 2 title",
  },
  {
    key: "home.highlights.2.description",
    geo: "ადაპტური ეკრანები, აპთან კავშირი და OTA განახლებები.",
    en: "Adaptive displays, app-linked controls, and OTA updates.",
    ru: "Адаптивные дисплеи, управление через приложение и OTA-обновления.",
    description: "Home highlight 2 description",
  },
  {
    key: "home.highlights.3.title",
    geo: "ჰიბრიდისთვის მზად პლატფორმები",
    en: "Hybrid-ready platforms",
    ru: "Платформы с готовностью к гибриду",
    description: "Home highlight 3 title",
  },
  {
    key: "home.highlights.3.description",
    geo: "დაბალი ემისიები და სწრაფი, გლუვი დინამიკა.",
    en: "Lower emissions with responsive torque delivery.",
    ru: "Сниженные выбросы и отзывчивая динамика крутящего момента.",
    description: "Home highlight 3 description",
  },
  {
    key: "home.slider.regionAria",
    geo: "მთავარი გვერდის გამორჩეული სლაიდები",
    en: "Homepage featured slides",
    ru: "Выделенные слайды главной страницы",
    description: "Home slider region aria",
  },
  {
    key: "home.slider.goToSlideAria",
    geo: "გადასვლა სლაიდზე {index}: {title}",
    en: "Go to slide {index}: {title}",
    ru: "Перейти к слайду {index}: {title}",
    description: "Home slider dot aria template",
  },

  {
    key: "models.title",
    geo: "მოდელების ხაზი",
    en: "Model lineup",
    ru: "Линейка моделей",
    description: "Models page title",
  },
  {
    key: "models.subtitle",
    geo: "იპოვეთ საუკეთესო მოდელი ქალაქისთვის, ოჯახისთვის და მოგზაურობისთვის.",
    en: "Find the right fit for city driving, family travel, and weekend escapes.",
    ru: "Найдите подходящую модель для города, семьи и поездок на выходных.",
    description: "Models page subtitle",
  },
  {
    key: "models.filters.searchLabel",
    geo: "ძებნა",
    en: "Search",
    ru: "Поиск",
    description: "Models filter search label",
  },
  {
    key: "models.filters.searchPlaceholder",
    geo: "მოდელის სახელით ძებნა",
    en: "Search by model name",
    ru: "Поиск по названию модели",
    description: "Models filter search placeholder",
  },
  {
    key: "models.filters.vehicleType",
    geo: "ავტომობილის ტიპი",
    en: "Vehicle type",
    ru: "Тип кузова",
    description: "Models filter vehicle type label",
  },
  {
    key: "models.filters.featuredOnly",
    geo: "მხოლოდ გამორჩეული მოდელები",
    en: "Featured models only",
    ru: "Только рекомендуемые модели",
    description: "Models filter featured checkbox",
  },
  {
    key: "models.filters.apply",
    geo: "ფილტრების გამოყენება",
    en: "Apply filters",
    ru: "Применить фильтры",
    description: "Models filter apply button",
  },
  {
    key: "models.filters.reset",
    geo: "გასუფთავება",
    en: "Reset",
    ru: "Сбросить",
    description: "Models filter reset button",
  },
  {
    key: "models.showingCount",
    geo: "ნაპოვნია {count} მოდელი",
    en: "Showing {count} models",
    ru: "Показано моделей: {count}",
    description: "Models count label",
  },
  {
    key: "models.empty",
    geo: "არჩეული ფილტრებისთვის მოდელი ვერ მოიძებნა.",
    en: "No models matched your filters. Try a different combination.",
    ru: "По выбранным фильтрам модели не найдены. Попробуйте изменить параметры.",
    description: "Models empty state",
  },
  {
    key: "models.card.featured",
    geo: "გამორჩეული",
    en: "Featured",
    ru: "Рекомендуется",
    description: "Model card featured badge",
  },
  {
    key: "models.card.viewDetails",
    geo: "დეტალები",
    en: "View details",
    ru: "Подробнее",
    description: "Model card details button",
  },
  {
    key: "models.card.bookTestDrive",
    geo: "ტესტ დრაივის დაჯავშნა",
    en: "Book test drive",
    ru: "Записаться на тест-драйв",
    description: "Model card book button",
  },
  {
    key: "models.detail.back",
    geo: "მოდელებზე დაბრუნება",
    en: "Back to models",
    ru: "Назад к моделям",
    description: "Model detail back link",
  },
  {
    key: "models.detail.keySpecs",
    geo: "ძირითადი მახასიათებლები",
    en: "Key specs",
    ru: "Ключевые характеристики",
    description: "Model detail specs title",
  },
  {
    key: "models.detail.notFoundTitle",
    geo: "მოდელი ვერ მოიძებნა",
    en: "Model not found",
    ru: "Модель не найдена",
    description: "Model detail not found metadata title",
  },
  {
    key: "models.detail.notFoundDescription",
    geo: "მითითებული მოდელი არ არსებობს.",
    en: "The requested model does not exist.",
    ru: "Запрошенная модель не существует.",
    description: "Model detail not found metadata description",
  },

  {
    key: "finance.title",
    geo: "ფინანსური კალკულატორი",
    en: "Finance calculator",
    ru: "Финансовый калькулятор",
    description: "Finance calculator title",
  },
  {
    key: "finance.subtitle",
    geo: "მიიღეთ სავარაუდო თვიური გადახდა ძირითადი პარამეტრების მიხედვით.",
    en: "Get an estimated monthly payment using core financing inputs.",
    ru: "Рассчитайте ориентировочный ежемесячный платеж по основным параметрам.",
    description: "Finance calculator subtitle",
  },
  {
    key: "finance.toggle.expandAria",
    geo: "ფინანსური კალკულატორის გახსნა",
    en: "Expand finance calculator",
    ru: "Раскрыть финансовый калькулятор",
    description: "Finance calculator expand button aria label",
  },
  {
    key: "finance.toggle.collapseAria",
    geo: "ფინანსური კალკულატორის დამალვა",
    en: "Collapse finance calculator",
    ru: "Свернуть финансовый калькулятор",
    description: "Finance calculator collapse button aria label",
  },
  {
    key: "finance.fields.vehiclePrice",
    geo: "ავტომობილის ფასი",
    en: "Vehicle price",
    ru: "Цена автомобиля",
    description: "Finance calculator vehicle price label",
  },
  {
    key: "finance.fields.downPayment",
    geo: "პირველი შენატანი",
    en: "Down payment",
    ru: "Первоначальный взнос",
    description: "Finance calculator down payment label",
  },
  {
    key: "finance.fields.downPaymentModeAmount",
    geo: "თანხა",
    en: "Amount",
    ru: "Сумма",
    description: "Finance calculator down payment amount mode",
  },
  {
    key: "finance.fields.downPaymentModePercent",
    geo: "პროცენტი",
    en: "Percent",
    ru: "Процент",
    description: "Finance calculator down payment percent mode",
  },
  {
    key: "finance.fields.loanTerm",
    geo: "სესხის ვადა",
    en: "Loan term",
    ru: "Срок кредита",
    description: "Finance calculator loan term label",
  },
  {
    key: "finance.fields.termUnit",
    geo: "თვე",
    en: "months",
    ru: "месяцев",
    description: "Finance calculator loan term unit",
  },
  {
    key: "finance.fields.apr",
    geo: "საპროცენტო განაკვეთი APR (%)",
    en: "APR (%)",
    ru: "APR (%)",
    description: "Finance calculator APR label",
  },
  {
    key: "finance.fields.advancedShow",
    geo: "დამატებითი პარამეტრების ჩვენება",
    en: "Show optional fields",
    ru: "Показать дополнительные поля",
    description: "Finance calculator show advanced fields",
  },
  {
    key: "finance.fields.advancedHide",
    geo: "დამატებითი პარამეტრების დამალვა",
    en: "Hide optional fields",
    ru: "Скрыть дополнительные поля",
    description: "Finance calculator hide advanced fields",
  },
  {
    key: "finance.fields.tradeIn",
    geo: "Trade-in ღირებულება",
    en: "Trade-in value",
    ru: "Стоимость trade-in",
    description: "Finance calculator trade-in label",
  },
  {
    key: "finance.fields.fees",
    geo: "დამატებითი საკომისიო",
    en: "Fees",
    ru: "Сборы",
    description: "Finance calculator fees label",
  },
  {
    key: "finance.results.monthlyPayment",
    geo: "თვიური გადასახადი",
    en: "Monthly payment",
    ru: "Ежемесячный платеж",
    description: "Finance calculator monthly payment result label",
  },
  {
    key: "finance.results.loanPrincipal",
    geo: "სესხის ძირი",
    en: "Loan principal",
    ru: "Сумма кредита",
    description: "Finance calculator principal result label",
  },
  {
    key: "finance.results.totalPaid",
    geo: "სულ გადასახდელი",
    en: "Total paid",
    ru: "Итого к оплате",
    description: "Finance calculator total paid result label",
  },
  {
    key: "finance.results.totalInterest",
    geo: "სულ პროცენტი",
    en: "Total interest",
    ru: "Всего процентов",
    description: "Finance calculator total interest result label",
  },
  {
    key: "finance.validation.title",
    geo: "გადაამოწმეთ პარამეტრები",
    en: "Please review your inputs",
    ru: "Проверьте введенные параметры",
    description: "Finance calculator validation summary title",
  },
  {
    key: "finance.validation.principalPositive",
    geo: "საბოლოო სესხის ძირი უნდა იყოს 0-ზე მეტი.",
    en: "Calculated loan principal must be greater than 0.",
    ru: "Рассчитанная сумма кредита должна быть больше 0.",
    description: "Finance calculator principal validation",
  },
  {
    key: "finance.validation.aprNonNegative",
    geo: "APR უნდა იყოს 0 ან მეტი.",
    en: "APR must be 0 or higher.",
    ru: "APR должен быть 0 или больше.",
    description: "Finance calculator APR validation",
  },
  {
    key: "finance.validation.termPositive",
    geo: "სესხის ვადა უნდა იყოს 0-ზე მეტი.",
    en: "Loan term must be greater than 0.",
    ru: "Срок кредита должен быть больше 0.",
    description: "Finance calculator term validation",
  },
  {
    key: "finance.schedule.title",
    geo: "ამორტიზაციის მოკლე ჭრილი",
    en: "Amortization preview",
    ru: "Предварительный график выплат",
    description: "Finance calculator amortization table title",
  },
  {
    key: "finance.schedule.description",
    geo: "პირველი 12 თვის გადანაწილება ძირისა და პროცენტის მიხედვით.",
    en: "First 12 months split by principal and interest.",
    ru: "Первые 12 месяцев с разбивкой на тело кредита и проценты.",
    description: "Finance calculator amortization table description",
  },
  {
    key: "finance.schedule.month",
    geo: "თვე",
    en: "Month",
    ru: "Месяц",
    description: "Finance calculator amortization month column label",
  },
  {
    key: "finance.schedule.principalPaid",
    geo: "ძირის გადახდა",
    en: "Principal paid",
    ru: "Погашение тела кредита",
    description: "Finance calculator amortization principal paid column label",
  },
  {
    key: "finance.schedule.interestPaid",
    geo: "პროცენტი",
    en: "Interest paid",
    ru: "Проценты",
    description: "Finance calculator amortization interest paid column label",
  },
  {
    key: "finance.schedule.remainingBalance",
    geo: "დარჩენილი ბალანსი",
    en: "Remaining balance",
    ru: "Остаток долга",
    description: "Finance calculator amortization remaining balance column label",
  },

  {
    key: "booking.title",
    geo: "ტესტ დრაივის დაჯავშნა",
    en: "Book a test drive",
    ru: "Записаться на тест-драйв",
    description: "Booking page title",
  },
  {
    key: "booking.subtitle",
    geo: "მიუთითეთ სასურველი მოდელი და დრო. ჩვენი გუნდი დაგიკავშირდებათ დადასტურებისთვის.",
    en: "Share your preferred model and schedule. Our team will confirm your booking.",
    ru: "Укажите предпочитаемую модель и время. Наша команда подтвердит запись.",
    description: "Booking page subtitle",
  },
  { key: "booking.form.name", geo: "სრული სახელი", en: "Full name", ru: "Полное имя", description: "Booking form name label" },
  { key: "booking.form.email", geo: "ელ-ფოსტა", en: "Email", ru: "Email", description: "Booking form email label" },
  { key: "booking.form.phone", geo: "ტელეფონი", en: "Phone", ru: "Телефон", description: "Booking form phone label" },
  {
    key: "booking.form.preferredModel",
    geo: "სასურველი მოდელი",
    en: "Preferred model",
    ru: "Предпочитаемая модель",
    description: "Booking form model label",
  },
  {
    key: "booking.form.anyModel",
    geo: "ნებისმიერი მოდელი",
    en: "Any model",
    ru: "Любая модель",
    description: "Booking form any model option",
  },
  {
    key: "booking.form.preferredDate",
    geo: "სასურველი თარიღი (GMT+4)",
    en: "Preferred date (GMT+4)",
    ru: "Предпочтительная дата (GMT+4)",
    description: "Booking form date label",
  },
  {
    key: "booking.form.preferredTime",
    geo: "სასურველი დრო (GMT+4)",
    en: "Preferred time (GMT+4)",
    ru: "Предпочтительное время (GMT+4)",
    description: "Booking form time label",
  },
  {
    key: "booking.form.selectTimeSlot",
    geo: "აირჩიეთ დრო",
    en: "Select a time slot",
    ru: "Выберите время",
    description: "Booking form time select placeholder",
  },
  {
    key: "booking.form.availableWindow",
    geo: "ხელმისაწვდომია ყოველდღე 9:00-დან 20:00-მდე.",
    en: "Available daily between 9:00 AM and 8:00 PM.",
    ru: "Доступно ежедневно с 9:00 до 20:00.",
    description: "Booking form time window hint",
  },
  {
    key: "booking.form.noSlotsToday",
    geo: "დღეს დროები დასრულებულია. აირჩიეთ მომდევნო თარიღი.",
    en: "No slots left for today. Please select a later date.",
    ru: "На сегодня свободных слотов нет. Выберите другую дату.",
    description: "Booking form no slots message",
  },
  {
    key: "booking.form.location",
    geo: "სასურველი ლოკაცია",
    en: "Preferred location",
    ru: "Предпочтительная локация",
    description: "Booking form location label",
  },
  {
    key: "booking.form.locationPlaceholder",
    geo: "ქალაქი ან დილერი",
    en: "City or dealership",
    ru: "Город или дилерский центр",
    description: "Booking form location placeholder",
  },
  {
    key: "booking.form.note",
    geo: "შენიშვნა (არასავალდებულო)",
    en: "Note (optional)",
    ru: "Комментарий (необязательно)",
    description: "Booking form note label",
  },
  {
    key: "booking.form.submit",
    geo: "დაჯავშნის გაგზავნა",
    en: "Submit booking",
    ru: "Отправить заявку",
    description: "Booking form submit button",
  },
  {
    key: "booking.form.submitting",
    geo: "იგზავნება...",
    en: "Submitting...",
    ru: "Отправка...",
    description: "Booking form submitting state",
  },
  {
    key: "booking.form.errors.generic",
    geo: "გთხოვთ გადაამოწმოთ მონიშნული ველები.",
    en: "Please review the highlighted fields.",
    ru: "Проверьте выделенные поля.",
    description: "Booking form generic validation error",
  },
  {
    key: "booking.form.errors.name",
    geo: "შეიყვანეთ სწორი სახელი.",
    en: "Please enter a valid name.",
    ru: "Введите корректное имя.",
    description: "Booking form name validation error",
  },
  {
    key: "booking.form.errors.email",
    geo: "შეიყვანეთ სწორი ელ-ფოსტა.",
    en: "Please enter a valid email address.",
    ru: "Введите корректный email.",
    description: "Booking form email validation error",
  },
  {
    key: "booking.form.errors.phone",
    geo: "შეიყვანეთ სწორი ტელეფონის ნომერი.",
    en: "Please enter a valid phone number.",
    ru: "Введите корректный номер телефона.",
    description: "Booking form phone validation error",
  },
  {
    key: "booking.form.errors.preferredModel",
    geo: "სასურველი მოდელი არასწორია.",
    en: "Preferred model is invalid.",
    ru: "Выбранная модель некорректна.",
    description: "Booking form model validation error",
  },
  {
    key: "booking.form.errors.preferredDateTime",
    geo: "აირჩიეთ სწორი თარიღი და დრო.",
    en: "Please select a valid preferred date and time.",
    ru: "Выберите корректные дату и время.",
    description: "Booking form date/time validation error",
  },
  {
    key: "booking.form.errors.location",
    geo: "შეიყვანეთ სწორი ლოკაცია.",
    en: "Please enter a valid location.",
    ru: "Введите корректную локацию.",
    description: "Booking form location validation error",
  },
  {
    key: "booking.form.errors.note",
    geo: "შენიშვნის ველი არასწორია.",
    en: "Note value is invalid.",
    ru: "Комментарий указан некорректно.",
    description: "Booking form note validation error",
  },
  {
    key: "booking.nextSteps.title",
    geo: "რა ხდება შემდეგ?",
    en: "What happens next?",
    ru: "Что дальше?",
    description: "Booking page next steps title",
  },
  {
    key: "booking.nextSteps.step1",
    geo: "1. ვამოწმებთ თქვენს არჩეულ თარიღსა და მოდელს.",
    en: "1. We review your preferred date and model.",
    ru: "1. Мы проверяем выбранные дату и модель.",
    description: "Booking page step 1",
  },
  {
    key: "booking.nextSteps.step2",
    geo: "2. კონსულტანტი დაგიდასტურებთ ხელმისაწვდომობას.",
    en: "2. A sales advisor confirms availability by email or phone.",
    ru: "2. Консультант подтверждает доступность по email или телефону.",
    description: "Booking page step 2",
  },
  {
    key: "booking.nextSteps.step3",
    geo: "3. მიიღებთ ვიზიტის საბოლოო დეტალებს.",
    en: "3. You receive final visit details and route information.",
    ru: "3. Вы получаете финальные детали визита.",
    description: "Booking page step 3",
  },
  {
    key: "booking.success.title",
    geo: "მოთხოვნა მიღებულია",
    en: "Booking request received",
    ru: "Заявка получена",
    description: "Booking success title",
  },
  {
    key: "booking.success.description",
    geo: "თქვენი ტესტ დრაივის მოთხოვნა წარმატებით გაიგზავნა. მალე დაგიკავშირდებით.",
    en: "Your test drive request has been submitted. Our team will contact you shortly.",
    ru: "Ваша заявка на тест-драйв отправлена. Мы свяжемся с вами в ближайшее время.",
    description: "Booking success description",
  },
  {
    key: "booking.success.reference",
    geo: "რეფერენსი: #{id}",
    en: "Reference: #{id}",
    ru: "Номер заявки: #{id}",
    description: "Booking success reference line",
  },
  {
    key: "booking.success.browseModels",
    geo: "მოდელების ნახვა",
    en: "Browse models",
    ru: "Смотреть модели",
    description: "Booking success browse models button",
  },
  {
    key: "booking.success.backHome",
    geo: "მთავარზე დაბრუნება",
    en: "Back home",
    ru: "На главную",
    description: "Booking success back home button",
  },

  {
    key: "about.title",
    geo: "შექმნილი თანამედროვე გადაადგილებისთვის",
    en: "Built for modern movement",
    ru: "Создано для современной мобильности",
    description: "About page title",
  },
  {
    key: "about.subtitle",
    geo: "Astra Motors ქმნის პრაქტიკულ ავტომობილებს პრემიუმ შეგრძნებით და ციფრული გამოცდილებით.",
    en: "Astra Motors develops practical vehicles with a premium feel and software-first experiences.",
    ru: "Astra Motors создает практичные автомобили с премиальным ощущением и цифровым опытом.",
    description: "About page subtitle",
  },
  {
    key: "about.cards.design.title",
    geo: "დიზაინის ენა",
    en: "Design language",
    ru: "Дизайн-язык",
    description: "About design card title",
  },
  {
    key: "about.cards.design.description",
    geo: "თანამედროვე სილუეტები აეროდინამიკური ხაზებით და გამძლე მასალებით.",
    en: "Contemporary silhouettes with aerodynamic detailing and durable materials.",
    ru: "Современные силуэты с аэродинамикой и долговечными материалами.",
    description: "About design card description",
  },
  {
    key: "about.cards.engineering.title",
    geo: "ინჟინერიული ფოკუსი",
    en: "Engineering focus",
    ru: "Инженерный фокус",
    description: "About engineering card title",
  },
  {
    key: "about.cards.engineering.description",
    geo: "გაწონასწორებული დაკიდება, დაბალი ხმაურის სალონი და უსაფრთხო ელექტრო არქიტექტურა.",
    en: "Tuned suspensions, low-noise cabins, and safety-first electrical architecture.",
    ru: "Настроенная подвеска, тихий салон и безопасная электрическая архитектура.",
    description: "About engineering card description",
  },
  {
    key: "about.cards.service.title",
    geo: "შემდგომი მომსახურება",
    en: "After-sales care",
    ru: "Послепродажный сервис",
    description: "About service card title",
  },
  {
    key: "about.cards.service.description",
    geo: "სერვისის ციფრული დაჯავშნა, გამჭვირვალე გეგმები და ეროვნული მხარდაჭერა.",
    en: "Nationwide support teams, digital service booking, and transparent maintenance plans.",
    ru: "Поддержка по стране, цифровая запись на сервис и прозрачные планы обслуживания.",
    description: "About service card description",
  },

  {
    key: "contact.title",
    geo: "კონტაქტი Astra Motors",
    en: "Contact Astra Motors",
    ru: "Свяжитесь с Astra Motors",
    description: "Contact page title",
  },
  {
    key: "contact.subtitle",
    geo: "დაუკავშირდით გაყიდვების, სერვისის ან ფლიტის კონსულტანტებს.",
    en: "Speak with sales, service, or fleet advisors.",
    ru: "Свяжитесь с отделом продаж, сервиса или корпоративных решений.",
    description: "Contact page subtitle",
  },
  {
    key: "contact.cards.sales.title",
    geo: "გაყიდვები",
    en: "Sales desk",
    ru: "Отдел продаж",
    description: "Contact sales card title",
  },
  {
    key: "contact.cards.sales.email",
    geo: "sales@astramotors.example",
    en: "sales@astramotors.example",
    ru: "sales@astramotors.example",
    description: "Contact sales email",
  },
  {
    key: "contact.cards.sales.phone",
    geo: "+1 (555) 018-4040",
    en: "+1 (555) 018-4040",
    ru: "+1 (555) 018-4040",
    description: "Contact sales phone",
  },
  {
    key: "contact.cards.service.title",
    geo: "სერვის ცენტრი",
    en: "Service center",
    ru: "Сервисный центр",
    description: "Contact service card title",
  },
  {
    key: "contact.cards.service.email",
    geo: "service@astramotors.example",
    en: "service@astramotors.example",
    ru: "service@astramotors.example",
    description: "Contact service email",
  },
  {
    key: "contact.cards.service.phone",
    geo: "+1 (555) 018-4041",
    en: "+1 (555) 018-4041",
    ru: "+1 (555) 018-4041",
    description: "Contact service phone",
  },
  {
    key: "contact.cards.visit.title",
    geo: "მისამართი",
    en: "Visit us",
    ru: "Наш адрес",
    description: "Contact visit card title",
  },
  {
    key: "contact.cards.visit.addressLine1",
    geo: "211 Harbor Avenue",
    en: "211 Harbor Avenue",
    ru: "211 Harbor Avenue",
    description: "Contact visit address line 1",
  },
  {
    key: "contact.cards.visit.addressLine2",
    geo: "Austin, TX 78701",
    en: "Austin, TX 78701",
    ru: "Austin, TX 78701",
    description: "Contact visit address line 2",
  },

  {
    key: "footer.description",
    geo: "თანამედროვე ავტომობილები ინტელექტუალური ტექნოლოგიებით და კომფორტზე ორიენტირებული ინტერიერით.",
    en: "Contemporary vehicles with connected technology, efficient powertrains, and comfort-first interiors.",
    ru: "Современные автомобили с цифровыми технологиями, эффективными силовыми установками и комфортным интерьером.",
    description: "Footer brand description",
  },
  { key: "footer.explore", geo: "დათვალიერება", en: "Explore", ru: "Разделы", description: "Footer explore heading" },
  { key: "footer.links.models", geo: "მოდელები", en: "Models", ru: "Модели", description: "Footer models link" },
  {
    key: "footer.links.bookTestDrive",
    geo: "ტესტ დრაივი",
    en: "Book Test Drive",
    ru: "Тест-драйв",
    description: "Footer book test drive link",
  },
  { key: "footer.links.about", geo: "ჩვენ შესახებ", en: "About", ru: "О нас", description: "Footer about link" },
  { key: "footer.contact", geo: "კონტაქტი", en: "Contact", ru: "Контакты", description: "Footer contact heading" },
  {
    key: "footer.contact.email",
    geo: "sales@astramotors.example",
    en: "sales@astramotors.example",
    ru: "sales@astramotors.example",
    description: "Footer contact email",
  },
  {
    key: "footer.contact.phone",
    geo: "+1 (555) 018-4040",
    en: "+1 (555) 018-4040",
    ru: "+1 (555) 018-4040",
    description: "Footer contact phone",
  },
  {
    key: "footer.contact.address",
    geo: "211 Harbor Avenue, Austin, TX",
    en: "211 Harbor Avenue, Austin, TX",
    ru: "211 Harbor Avenue, Austin, TX",
    description: "Footer contact address",
  },

  { key: "vehicleType.crossover", geo: "ქროსოვერი", en: "Crossover", ru: "Кроссовер", description: "Vehicle type" },
  { key: "vehicleType.coupe", geo: "კუპე", en: "Coupe", ru: "Купе", description: "Vehicle type" },
  { key: "vehicleType.hatchback", geo: "ჰეჩბექი", en: "Hatchback", ru: "Хэтчбек", description: "Vehicle type" },
  { key: "vehicleType.sedan", geo: "სედანი", en: "Sedan", ru: "Седан", description: "Vehicle type" },
  { key: "vehicleType.suv", geo: "SUV", en: "SUV", ru: "SUV", description: "Vehicle type" },
  { key: "vehicleType.truck", geo: "პიკაპი", en: "Truck", ru: "Пикап", description: "Vehicle type" },
  { key: "vehicleType.van", geo: "ვენი", en: "Van", ru: "Фургон", description: "Vehicle type" },
  { key: "vehicleType.wagon", geo: "უნივერსალი", en: "Wagon", ru: "Универсал", description: "Vehicle type" },
] as const;

async function seed() {
  for (const car of sampleCars) {
    await db
      .insert(cars)
      .values({
        name: car.nameGeo,
        nameGeo: car.nameGeo,
        nameEn: car.nameEn,
        nameRu: car.nameRu,
        slug: car.slug,
        priceFrom: car.priceFrom,
        bodyType: car.bodyType,
        description: car.descriptionGeo,
        descriptionGeo: car.descriptionGeo,
        descriptionEn: car.descriptionEn,
        descriptionRu: car.descriptionRu,
        featured: car.featured,
        specs: car.specs,
        images: car.images,
        updatedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: cars.slug,
        set: {
          name: car.nameGeo,
          nameGeo: car.nameGeo,
          nameEn: car.nameEn,
          nameRu: car.nameRu,
          priceFrom: car.priceFrom,
          bodyType: car.bodyType,
          description: car.descriptionGeo,
          descriptionGeo: car.descriptionGeo,
          descriptionEn: car.descriptionEn,
          descriptionRu: car.descriptionRu,
          featured: car.featured,
          specs: car.specs,
          images: car.images,
          updatedAt: new Date(),
        },
      });
  }

  await db
    .insert(content)
    .values({
      key: "homepage",
      value: homepageContent,
      updatedAt: new Date(),
    })
    .onConflictDoUpdate({
      target: content.key,
      set: {
        value: homepageContent,
        updatedAt: new Date(),
      },
    });

  for (const slide of sampleSlides) {
    await db
      .insert(homepageSlides)
      .values({
        ...slide,
        updatedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: homepageSlides.id,
        set: {
          title: slide.title,
          description: slide.description,
          imageUrl: slide.imageUrl,
          ctaLabel: slide.ctaLabel,
          ctaHref: slide.ctaHref,
          sortOrder: slide.sortOrder,
          isActive: slide.isActive,
          updatedAt: new Date(),
        },
      });
  }

  for (const entry of i18nSeedEntries) {
    await db
      .insert(i18nStrings)
      .values({
        key: entry.key,
        geo: entry.geo,
        en: entry.en,
        ru: entry.ru,
        description: entry.description,
        updatedAt: new Date(),
      })
      .onConflictDoUpdate({
        target: i18nStrings.key,
        set: {
          geo: entry.geo,
          en: entry.en,
          ru: entry.ru,
          description: entry.description,
          updatedAt: new Date(),
        },
      });
  }

  console.log("Seed completed");
}

seed()
  .catch((error) => {
    console.error("Seed failed", error);
    process.exit(1);
  })
  .finally(async () => {
    process.exit(0);
  });
